website:
  title: "Dóra Szefcsik"                             
  description: "Data Analyst"   
  image: img/my_image.jpg
  
  
  navbar:
    pinned: true
    background: light
    

    left:
      - text: "Projects"
        href: projects/index.qmd
 
    
    right:
      - icon: envelope
        aria-label: email
        href: "mailto:dora.szefcsik@gmail.com"  
      - icon: github
        href: https://github.com/doraszefcsik
      - icon: linkedin
        href: https://www.linkedin.com/in/doraszefcsik/

  
  page-footer: 
    left: "Copyright 2023, Dóra Szefcsik"

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

format:
  html:
    fontsize: 1.1em
    theme: cosmo
    toc: true
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true